services:
  db:
    image: postgres:16.6-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Bright#1270
      POSTGRES_DB: blog_post_manager

  api:
    build: apps/api
    depends_on:
      - db
    volumes:
      - ./apps/api:/api
    environment:
      - DATABASE_URL=postgresql://postgres:Bright#1270@db:5432/blog_post_manager
    ports:
      - "8000:8000"

volumes:
  postgres_data:
